### ISSUE TITLE
鉴于有人说前台界面有点粗糙，考虑月底换上新博客模版

### ISSUE THREAD

**Issue by ycrao** [douyasi/yascmf#1]
鉴于论坛有人说[界面有点粗糙](https://phphub.org/topics/558)，本月月底打算换上新博客模版，风格偏向简约 `markdown` 型，可能不支持响应式手机。

目前前台为了快捷展示，使用了 `bootstrap` ， `bootstrap` 前端框架文档丰富，比较适合开发者套取页面；说句实话，嫌界面太丑的，我也不知道到底丑在哪儿。

话虽说如此，但希望：您不要因为界面不够美观，连一个star :+1: 都不舍得给吧！

我觉得本套源码后端学习意义大于前端学习意义，您应该从本套源码中学习更多的 `Laravel`（特别是新版5） 基础知识，而非设计与前端上知识，实际上，前台模版你也可以自行尝试更换，或者自行修改 `Blog` 控制器。

**Comment by ghmaga** [comment]
赞

**Comment by ycrao** [comment]
因工作原因换新模板工作可能延后

**Comment by ycrao** [comment]
新版后台的 YASCMF 已发布一段时间，前后台页面模版均基于 `Bootstrap` ，未来可能不会在模版上面有太多变化，有一定财力的人，可考虑买一款 中意的 `Bootstrap` 博客模版。
