### ISSUE TITLE
内容管理的页面不能批量删除

### ISSUE THREAD

**Issue by Flyu** [douyasi/yascmf#2]
内容管理的页面不能批量删除

**Comment by ycrao** [comment]
当前版本的源码还是比较粗糙的，所以我认为本源码的学习意义大于实用意义。

批量删除是在当前版本中是留白的，您可以考虑自行实现，遵循 `RESTFUL` 基本规范即可：
比如在控制器中建立`batchDelete($ids)`方法，该方法接受过来数据 `$ids` 将是等待批量删除的id数组，批量删除路由可以是：
```
Route::delete('/article', ['uses'=>'Admin\AdminArticleController@batchDelete']);
```
关于批量删除的 `RESTFUL` 具体实现方案目前并未统一，请参阅以下网址：  http://www.ruanyifeng.com/blog/2014/05/restful_api.html
http://www.v2ex.com/t/154258
