### ISSUE TITLE
打算使用 AdminLTE 来构建新的后台

### ISSUE THREAD

**Issue by ycrao** [douyasi/yascmf#3]
`AdminLTE` 是一个遵循 MIT 开源协议 的后台管理模版：https://github.com/almasaeed2010/AdminLTE

本人打算使用它来构建新的后台，主要是因为： `AdminLTE` 模版基于 `Bootstrap` 构建，响应式布局，同时支持手机和电脑浏览器，`Bootstrap` 相关文档方面也比较充足，开发者通过阅读文档可以很方便地在它基础上进行二次修改。 

具体完成的时间未定，可能在5月中旬。期间，会完善与加强 `YASCMF` 某些功能模块（前台主题模版 [#1](/douyasi/yascmf/issues/1) 也会一并替换），请耐心等待！

**Comment by shjchen** [comment]
赞一个

**Comment by ycrao** [comment]
已初步完成，关闭此issue
