### ISSUE TITLE
系统做的很好,可是后台界面在chrome下有点问题

### ISSUE THREAD

**Issue by gantoday** [douyasi/yascmf#5]
谢谢开发者,你的系统帮我省下了许多麻烦,但是发现了几个小问题:
1.文章管理的预览点了没反应
2.缩略图预览,鼠标移上去弹出预览,然后鼠标移开图也不消失,正常人思维应该鼠标移开预览图消失
用的是Mac下的chrome最新版

**Comment by ycrao** [comment]
预览本来是对应前台文章或单页页面链接，需考虑前台slug链接的生成，故暂时略去；
缩略图预览的确存在你所说的问题，后期版本可能考虑另外一种比较人性化的展示方式。
