### ISSUE TITLE
找不到表

### ISSUE THREAD

**Issue by programlife555** [douyasi/yascmf#9]
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'web_yascmf.yascmf_assigned_roles' doesn't exist (SQL: select `yascmf_roles`.*, `yascmf_assigned_roles`.`user_id` as `pivot_user_id`, `yascmf_assigned_roles`.`role_id` as `pivot_role_id` from `yascmf_roles` inner join `yascmf_assigned_roles` on `yascmf_roles`.`id` = `yascmf_assigned_roles`.`role_id` where `yascmf_assigned_roles`.`user_id` = 1)

**Comment by ycrao** [comment]
数据库有没有导入呢？本项目没有使用数据库迁移功能。
